server:
  port: 8081
  tomcat:
    connection-timeout: 18000000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jingbo?useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: jingbo
    password: jingbo
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 30000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    mode: HTML
    cache: false
    cache-period: 0
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.jingbo.houtai.entity
  configuration:
    map-underscore-to-camel-case: true

superuser:
  name: root
  password: admin
logging:
  config: classpath:logback.xml
file:
  pdf:
    upload:
      path: uploadfile/pdf
  img:
    upload:
      path: uploadfile/images
  multipart:
  apk:
    upload:
      path: uploadfile/apk

